### ISSUE TITLE
script crashes asyncio.exceptions.CancelledError

### ISSUE THREAD

**Issue by darrynza** [p4kl0nc4t/wabf#5]
`(most recent call last):
  File "/home/bettyj/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 750, in transfer_data
    message = await self.read_message()
  File "/home/bettyj/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 819, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/bettyj/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 895, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/bettyj/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 971, in read_frame
    frame = await Frame.read(
  File "/home/bettyj/.local/lib/python3.9/site-packages/websockets/legacy/framing.py", line 55, in read
    data = await reader(2)
  File "/usr/lib/python3.9/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bettyj/wabf/wabf.py", line 137, in <module>
    main()  # noqa
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/bettyj/wabf/wabf.py", line 133, in main
    asyncio.run(amain(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/bettyj/wabf/wabf.py", line 50, in amain
    status = await check(whatsapp, jid)
  File "/home/bettyj/wabf/wabf.py", line 69, in check
    await whatsapp.websocket.send_message(message)
  File "/home/bettyj/.local/lib/python3.9/site-packages/kyros/websocket.py", line 199, in send_message
    await self.websocket.send(message.serialize(self.get_keys()))
  File "/home/bettyj/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 471, in send
    await self.ensure_open()
  File "/home/bettyj/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
`
runs for about 5 minutes then the above...

**Comment by lc-at** [comment]
I think this issue is correlated with the https://github.com/p4kl0nc4t/kyros/issues/18 issue.
